# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen_principal', models.ImageField(blank=True, upload_to='')),
                ('imagen_1', models.ImageField(blank=True, upload_to='')),
                ('imagen_2', models.ImageField(blank=True, upload_to='')),
                ('descripcion', models.TextField()),
                ('info_destacada', models.TextField()),
                ('info_adicional', models.TextField()),
                ('descripcion_breve', models.CharField(max_length=255)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='casting',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.Categoria'),
        ),
    ]
