# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_auto_20170313_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casting',
            name='imagen_1',
            field=models.ImageField(blank=True, upload_to='casting'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='imagen_2',
            field=models.ImageField(blank=True, upload_to='casting'),
        ),
    ]
