# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_auto_20170602_1753'),
        ('casting', '0002_auto_20170514_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='color_cabello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Cabellos'),
        ),
        migrations.AddField(
            model_name='casting',
            name='color_ojos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Ojos'),
        ),
        migrations.AddField(
            model_name='casting',
            name='etnia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Etnia'),
        ),
        migrations.AddField(
            model_name='casting',
            name='genero',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Pais'),
        ),
        migrations.AddField(
            model_name='casting',
            name='publico',
            field=models.BooleanField(default=True),
        ),
    ]
