# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20170608_2224'),
        ('casting', '0003_auto_20170602_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='casting',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='casting',
            name='publico',
        ),
        migrations.AddField(
            model_name='casting',
            name='tatuaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filtro',
            name='id_casting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.Casting'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='id_generos',
            field=models.ManyToManyField(to='frontend.GeneroArtistico'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='id_talento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.TipoArte'),
        ),
    ]
