# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_auto_20170403_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='audicion',
            name='ganador',
            field=models.BooleanField(default=False),
        ),
    ]
