# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_remove_casting_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
