# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0006_casting_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casting',
            name='publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='casting',
            name='tatuaje',
            field=models.NullBooleanField(default=None),
        ),
    ]
