# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100, verbose_name='Centro de Estudios')),
                ('fecha_inicio_estudio', models.DateField(verbose_name='Fecha inicio estudios')),
                ('fecha_fin_estudio', models.DateField(blank=True, null=True, verbose_name='Fecha culmino estudios')),
                ('estudiando_actualmente', models.BooleanField(default=False, verbose_name='Estudiando actualmente')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Educacion_usuario',
                'verbose_name_plural': 'Educacion',
                'verbose_name': 'Educacion',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_desde', models.DateField(verbose_name='Desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Desde')),
                ('trabajo_actual', models.BooleanField(default=False, verbose_name='Laborando actualmente?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Experiencia_usuario',
                'verbose_name_plural': 'Experiencias',
                'verbose_name': 'Experiencia',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=100, verbose_name='Culster')),
                ('archivo', models.CharField(max_length=100, verbose_name='Archivo')),
                ('nombre_archivo', models.CharField(max_length=100, verbose_name='Nombre del Archivo')),
                ('tipo_archivo', models.CharField(max_length=1, verbose_name='Tipo de archivo')),
                ('estado', models.CharField(default='R', max_length=1, verbose_name='Estado del archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Archivos_multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
                'verbose_name': 'Archivo Multimedia',
            },
        ),
    ]
