# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0002_auto_20170323_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(blank=True, upload_to='mensajes')),
                ('imagen_1', models.ImageField(blank=True, upload_to='casting')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_destino', to=settings.AUTH_USER_MODEL)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_origen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
