# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_auto_20170404_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=3)),
                ('bandera', models.ImageField(blank=True, upload_to='idiomas')),
            ],
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Hasta'),
        ),
    ]
