# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='57dc9b20-cc5b-40dc-9ba2-83e5f60417ab', max_length=100, unique=True),
        ),
    ]
