# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='44c44a35-af8b-430e-8454-92c770ffe4ba', max_length=100, unique=True),
        ),
    ]
