# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='09ac4d7b-b607-4729-869d-e480dc1ca73a', max_length=100, unique=True),
        ),
    ]
