# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170225_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='01821e81-9194-4d5f-93e7-4b25922dbc52', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='usuarioarte',
            name='id_arte',
        ),
        migrations.AddField(
            model_name='usuarioarte',
            name='id_arte',
            field=models.ForeignKey(db_column='Idtalento', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.TipoArte'),
        ),
        migrations.RemoveField(
            model_name='usuarioarte',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuarioarte',
            name='id_usuario',
            field=models.ForeignKey(db_column='Idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
