# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20170404_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='68a5954f-25bc-4c04-8342-8a7e6760a098', max_length=100, unique=True),
        ),
    ]
