# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20170305_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='0a541329-8d8c-424f-af75-ed74a809d3f8', max_length=100, unique=True),
        ),
    ]
