# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20170305_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='51c06909-b540-421f-91d3-a7aad6188acf', max_length=100, unique=True),
        ),
    ]
