# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20161118_2010'),
        ('frontend', '0005_auto_20170404_2217'),
    ]

    operations = [
    ]
