# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20170306_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generoartistico',
            name='id_tipo_arte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_arte', to='frontend.TipoArte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='cba299a4-2183-4370-9fb4-c82c33f039ae', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioartegenero',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='frontend.GeneroArtistico'),
        ),
        migrations.AlterField(
            model_name='usuarioartegenero',
            name='id_usuario',
            field=models.ForeignKey(db_column='Idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
