# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20170412_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intereses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Interes')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuarioarte',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='589c660a-bdb6-46cb-9c76-6f006884f43b', max_length=100, unique=True),
        ),
    ]
