# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20170310_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generoartistico',
            name='id_tipo_arte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artegenero', to='frontend.TipoArte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='d49b073b-2214-43a6-a661-6da0af027ec2', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioarte',
            name='id_arte',
            field=models.ForeignKey(db_column='Idtalento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_arte', to='frontend.TipoArte'),
        ),
        migrations.AlterField(
            model_name='usuarioarte',
            name='id_usuario',
            field=models.ForeignKey(db_column='Idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_arte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarioartegenero',
            name='id_usuario',
            field=models.ForeignKey(db_column='Idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_genero', to=settings.AUTH_USER_MODEL),
        ),
    ]
