# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20170310_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='06ed05c7-fbb2-4413-83fb-488d05e4584e', max_length=100, unique=True),
        ),
    ]
