# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20170313_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='02906aa5-c9dd-4b68-b03c-b50c3c183f9b', max_length=100, unique=True),
        ),
    ]
