# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20170414_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Sector Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SectorProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Proveedor')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='398b17c3-7c49-4ec5-97d2-c5c24d8aa68e', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sectorproveedor',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectorproveedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
