# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20170313_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='2a6128ef-4333-469d-85cf-d67ea1915559', max_length=100, unique=True),
        ),
    ]
