# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20170417_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='industria',
            name='tipo',
            field=models.CharField(choices=[('I', 'INDUSTRIA'), ('P', 'PROVEEDOR')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='c1e8afdc-706f-4658-8c68-cdbc96ffe7a4', max_length=100, unique=True),
        ),
    ]
