# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20170419_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='130eafdb-3fec-46c6-9c19-b1bce44c8bc8', max_length=100, unique=True),
        ),
    ]
