# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20170428_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='51d4296a-3196-4849-957f-7902e6453d74', max_length=100, unique=True),
        ),
    ]
