# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20170504_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='710c98d2-b672-4822-9a08-e166ab9b8255', max_length=100, unique=True),
        ),
    ]
