# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20170504_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='45db1e54-7844-43c3-bfde-4e4f72af61cd', max_length=100, unique=True),
        ),
    ]
