# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20170512_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=3)),
                ('bandera', models.ImageField(blank=True, upload_to='pais')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='2f0cb058-222b-4fd1-b885-050ec1736c2c', max_length=100, unique=True),
        ),
    ]
