# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20170513_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.ForeignKey(default=227, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='frontend.Pais'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='3d92676e-51c7-4b84-ae05-a3a7d55b8939', max_length=100, unique=True),
        ),
    ]
