# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20170513_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industria',
            name='tipo',
            field=models.CharField(choices=[('I', 'INDUSTRIA'), ('P', 'PROVEEDOR'), ('F', 'FANATICO')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='7e6a6c96-ccda-4fff-8767-94ff15b7d57f', max_length=100, unique=True),
        ),
    ]
