# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20170513_1929'),
        ('frontend', '0002_auto_20170514_0115'),
    ]

    operations = [
    ]
