# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='intereses',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='intereses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='d597e61c-abcf-4e51-b6a3-0b56c4f7f95a', max_length=100, unique=True),
        ),
    ]
