# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20170524_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='prefijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='c486e162-25a6-483f-9ae3-ebed93337715', max_length=100, unique=True),
        ),
    ]
