# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_auto_20170528_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='2933b1e9-4c53-402b-b86b-4c8032645956', max_length=100, unique=True),
        ),
    ]
