# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_auto_20170528_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Pais')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='5609e5ba-14a6-4dad-8d4d-c56f801c4570', max_length=100, unique=True),
        ),
    ]
