# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20170529_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='7cb4a343-b68d-42a6-929f-38f10317e370', max_length=100, unique=True),
        ),
    ]
