# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_auto_20170529_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='9fe08f92-d28e-43ff-849f-c64274e2041d', max_length=100, unique=True),
        ),
    ]
