# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_auto_20170529_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='72c1b946-5511-411e-b287-c99ead712820', max_length=100, unique=True),
        ),
    ]
