# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20170529_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='7be1c5f1-2636-4e54-8dc7-9bd614fe1f0e', max_length=100, unique=True),
        ),
    ]
