# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_auto_20170602_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='f63351d3-db44-4426-b37e-fe92fe868ba4', max_length=100, unique=True),
        ),
    ]
