# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20170608_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='71b6f114-6da1-4b79-b0dd-2b52a8df74d0', max_length=100, unique=True),
        ),
    ]
