# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_auto_20170609_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='a873c9ea-3b9a-4036-8ecc-bdc2305ea9bb', max_length=100, unique=True),
        ),
    ]
