# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_auto_20170714_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='1528fb95-f6f8-4d60-89f2-169e9d680433', max_length=100, unique=True),
        ),
    ]
